FROM ubuntu AS builder
RUN apt update \
    && apt install -y cmake \
                      git \
                      g++ \
                      libboost-all-dev \
                      libcurl4-openssl-dev \
    && apt clean
RUN git clone https://github.com/akhfa/TebakAngka.git \
    && cd TebakAngka \
    && cmake CMakeLists.txt \
    && make \
    && mv TebakAngka /usr/local/bin/ \
    && cd .. \
    && rm -rf TebakAngka

FROM ubuntu
RUN apt update \
    && apt install -y libboost-all-dev \
                      libcurl4-openssl-dev \
    && apt clean
COPY --from=builder /usr/local/bin/TebakAngka /usr/local/bin/
EXPOSE 18080
ENTRYPOINT [ "TebakAngka", "aaa", "bbb" ]
