version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /mnt:/prometheus
    labels:
      - "traefik.frontend.rule=Host:tes-prome.akhfa.me"
      - "traefik.port=9090"
  grafana:
    image: grafana/grafana
    labels:
      - "traefik.frontend.rule=Host:tes-grafana.akhfa.me"
      - "traefik.port=3000"
